In [2]:
import numpy as np
un_panda_numpy=np.array([100,5,20,80])
un_panda_numpy

array([100,   5,  20,  80])

In [4]:
famille_panda=np.array([[100,5,20,80],[80,5,12,120],[120,15,20,60]]);famille_panda

array([[100,   5,  20,  80],
       [ 80,   5,  12, 120],
       [120,  15,  20,  60]])

In [10]:
famille_panda[:,0]

array([100,  80, 120])

In [13]:
import pandas as pd
famille_panda_df=pd.DataFrame(famille_panda)
famille_panda_df

0   1   2    3
0  100   5  20   80
1   80   5  12  120
2  120  15  20   60

In [16]:
famille_panda_df=pd.DataFrame(famille_panda,["maman","bebe","papa"],["pattes","poils","queue","ventre"])
famille_panda_df

pattes  poils  queue  ventre
maman     100      5     20      80
bebe       80      5     12     120
papa      120     15     20      60

In [25]:
a=famille_panda_df.ventre

In [26]:
type(a)

pandas.core.series.Series

In [31]:
a

maman     80
bebe     120
papa      60
Name: ventre, dtype: int64

In [27]:
b=famille_panda_df["ventre"].values

In [32]:
b

array([ 80, 120,  60])

In [37]:
for a,b in famille_panda_df.iterrows():
    print("voici le panda",a, "de mesures\n",b)

voici le panda maman de mesures
 pattes    100
poils       5
queue      20
ventre     80
Name: maman, dtype: int64
voici le panda bebe de mesures
 pattes     80
poils       5
queue      12
ventre    120
Name: bebe, dtype: int64
voici le panda papa de mesures
 pattes    120
poils      15
queue      20
ventre     60
Name: papa, dtype: int64


In [42]:
famille_panda_df.iloc[2]

pattes    120
poils      15
queue      20
ventre     60
Name: papa, dtype: int64

In [45]:
famille_panda_df.loc["papa"]

pattes    120
poils      15
queue      20
ventre     60
Name: papa, dtype: int64

In [50]:
masque=famille_panda_df["ventre"]==80
pandas_80=famille_panda_df[masque]

In [52]:
pandas_80

pattes  poils  queue  ventre
maman     100      5     20      80

In [56]:
famille_panda_df[~(famille_panda_df.ventre==80)]

pattes  poils  queue  ventre
bebe      80      5     12     120
papa     120     15     20      60

In [60]:
autres_pandas=pd.DataFrame([[10,20,30,40],[120,15,20,60]], ["luc","michel"],famille_panda_df.columns)

In [61]:
autres_pandas

pattes  poils  queue  ventre
luc         10     20     30      40
michel     120     15     20      60

In [69]:
famille_panda_df=famille_panda_df.append(autres_pandas)
famille_panda_df

pattes  poils  queue  ventre
maman      100      5     20      80
bebe        80      5     12     120
papa       120     15     20      60
luc         10     20     30      40
michel     120     15     20      60
luc         10     20     30      40
michel     120     15     20      60

In [70]:
famille_panda_df=famille_panda_df.drop_duplicates()

In [77]:
famille_panda_df

pattes  poils  queue  ventre sexe
maman     100      5     20      80    f
bebe       80      5     12     120    f
papa      120     15     20      60    m
luc        10     20     30      40    m

In [76]:
famille_panda_df["sexe"]

maman    f
bebe     f
papa     m
luc      m
Name: sexe, dtype: object

In [79]:
famille_panda_df.sexe.unique()

array(['f', 'm'], dtype=object)

In [82]:
import os
os.getcwd()

'/home/ec2-user/Notebooks'

In [84]:
data=pd.read_csv("hubble_data.csv",sep=",")

In [86]:
type(data)

pandas.core.frame.DataFrame